package tokens;

public enum TokenType {
    MAIN, INT, FLOAT, CIN, COUT, IF, ELSE, WHILE, // KEYWORDS

    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO, // ARITHMETIC OPERATORS

    EQUAL, NOT_EQUAL, LESS_THAN_OR_EQUAL, LESS_THAN, GREATER_THAN_OR_EQUAL, GREATER_THAN, // COMPARISON OPERATORS

    AND, OR, // LOGICAL OPERATORS

    ASSIGNMENT, // ASSIGNMENT OPERATOR

    INPUT_OPERATOR, OUTPUT_OPERATOR, // IO OPERATORS

    OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_BRACE, CLOSE_BRACE, SEMICOLON, // SEPARATORS

    IDENTIFIER, INTEGER_CONSTANT, FLOAT_CONSTANT, STRING_CONSTANT, // IDENTIFIERS, CONSTANTS

    END_MARKER,
}
